import Home from "@/app/page";
import { HomestayStatus } from "@prisma/client";

export const adminUsers = [
  {
    id: "admin1",
    username: "admin",
    password: "admin123",
    name: "Admin User",
    email: "admin@homestay.com",
    role: "admin",
  },
];

export const mockHomestays = [
  {
    id: "1",
    name: "Sunset Beach Villa",
    location:[16.0672, 108.2210],
    address: "Đà Nẵng",
    description:
      "Biệt thự hướng biển tuyệt đẹp với tầm nhìn panorama ra biển Đà Nẵng. Nằm cách bãi biển Mỹ Khê chỉ 5 phút đi bộ.",
    price: 1200000,
    rating: 4.8,
    maxGuests: 6,
    images: [
      "/images/sunset-beach-villa-1.png",
      "/images/sunset-beach-villa-2.png",
      "/images/sunset-beach-villa-3.png",
    ],
    amenities: [
      "Wifi",
      "Bể bơi",
      "Bếp",
      "Máy lạnh",
      "Bãi đỗ xe",
      "TV",
      "Máy giặt",
    ],
    status: HomestayStatus.ACTIVE,
    createdAt: "2023-01-15T08:30:00Z",
    updatedAt: "2023-06-20T14:45:00Z",
    hostId: "host1",
    totalRooms: 3,
    allowsPartialBooking: true,
    featured: true,
  },
  {
    id: "2",
    name: "Mountain Retreat",
    location: [11.9429, 108.4551],
    address: "Đà Lạt",
    description:
      "Căn nhà gỗ ấm cúng nằm giữa rừng thông Đà Lạt. Với thiết kế mộc mạc nhưng tiện nghi đầy đủ.",
    price: 850000,
    rating: 4.6,
    maxGuests: 4,
    images: [
      "/images/mountain-retreat-1.png",
      "/images/mountain-retreat-2.png",
      "/images/mountain-retreat-3.png",
    ],
    amenities: ["Wifi", "Lò sưởi", "Bếp", "Máy lạnh", "TV", "Máy giặt"],
    status: HomestayStatus.PENDING,
    createdAt: "2023-02-10T10:15:00Z",
    updatedAt: "2023-07-05T09:30:00Z",
    hostId: "host2",
    totalRooms: 2,
    allowsPartialBooking: false,
    featured: false,
  },
  {
    id: "3",
    name: "Riverside Cottage",
    location: [15.8801, 108.338],
    address: "Hội An",
    description:
      "Ngôi nhà nhỏ xinh nằm bên dòng sông Thu Bồn thơ mộng. Từ đây, bạn có thể dễ dàng đi bộ đến phố cổ Hội An trong vòng 10 phút.",
    price: 950000,
    rating: 4.7,
    maxGuests: 3,
    images: [
      "/images/riverside-cottage-1.png",
      "/images/riverside-cottage-2.png",
      "/images/riverside-cottage-3.png",
    ],
    amenities: ["Wifi", "Bếp", "Máy lạnh", "TV", "Máy giặt", "Ban công"],
    status: HomestayStatus.MAINTENANCE,
    createdAt: "2023-03-05T11:45:00Z",
    updatedAt: "2023-08-12T16:20:00Z",
    hostId: "host1",
    totalRooms: 1,
    allowsPartialBooking: true,
    featured: false,
  },
  {
    id: "4",
    name: "City Center Apartment",
    location: [10.7769, 106.6958],
    address: "Hồ Chí Minh",
    description:
      "Căn hộ hiện đại nằm ở trung tâm Quận 1, TP.HCM. Với vị trí đắc địa, bạn có thể dễ dàng khám phá các điểm du lịch nổi tiếng.",
    price: 1100000,
    rating: 4.5,
    maxGuests: 4,
    images: [
      "/images/city-center-apartment-1.png",
      "/images/city-center-apartment-2.png",
      "/images/city-center-apartment-3.png",
    ],
    amenities: ["Wifi", "Bếp", "Máy lạnh", "TV", "Máy giặt", "Bể bơi chung"],
    status: HomestayStatus.ACTIVE,
    createdAt: "2023-04-20T09:00:00Z",
    updatedAt: "2023-09-01T13:10:00Z",
    hostId: "host3",
    totalRooms: 2,
    allowsPartialBooking: false,
    featured: true,
  },
  {
    id: "5",
    name: "Lakeside Villa",
    location: [21.0285, 105.8542],
    address: "Hà Nội",
    description:
      "Biệt thự sang trọng bên Hồ Tây, Hà Nội. Không gian rộng rãi với kiến trúc hiện đại kết hợp nét truyền thống.",
    price: 1500000,
    rating: 4.9,
    maxGuests: 8,
    images: [
      "/images/lakeside-villa-1.png",
      "/images/lakeside-villa-2.png",
      "/images/lakeside-villa-3.png",
    ],
    amenities: [
      "Wifi",
      "Bể bơi",
      "Bếp",
      "Máy lạnh",
      "Bãi đỗ xe",
      "TV",
      "Máy giặt",
      "Sân vườn",
    ],
    status: HomestayStatus.ACTIVE,
    createdAt: "2023-05-15T14:30:00Z",
    updatedAt: "2023-10-10T11:25:00Z",
    hostId: "host2",
    totalRooms: 4,
    allowsPartialBooking: true,
    featured: false,
  },
];

export const mockCustomers = [
  {
    id: "1",
    name: "Nguyễn Văn A",
    email: "nguyenvana@example.com",
    phone: "0901234567",
    address: "123 Đường Lê Lợi, Quận 1, TP.HCM",
    createdAt: "2023-01-10T08:00:00Z",
    totalBookings: 5,
    status: "active",
  },
  {
    id: "2",
    name: "Trần Thị B",
    email: "tranthib@example.com",
    phone: "0912345678",
    address: "456 Đường Nguyễn Huệ, Quận 1, TP.HCM",
    createdAt: "2023-02-15T10:30:00Z",
    totalBookings: 3,
    status: "active",
  },
  {
    id: "3",
    name: "Lê Văn C",
    email: "levanc@example.com",
    phone: "0923456789",
    address: "789 Đường Trần Hưng Đạo, Quận 5, TP.HCM",
    createdAt: "2023-03-20T14:45:00Z",
    totalBookings: 2,
    status: "inactive",
  },
  {
    id: "4",
    name: "Phạm Thị D",
    email: "phamthid@example.com",
    phone: "0934567890",
    address: "101 Đường Hai Bà Trưng, Quận 3, TP.HCM",
    createdAt: "2023-04-25T09:15:00Z",
    totalBookings: 1,
    status: "active",
  },
  {
    id: "5",
    name: "Hoàng Văn E",
    email: "hoangvane@example.com",
    phone: "0945678901",
    address: "202 Đường Võ Văn Tần, Quận 3, TP.HCM",
    createdAt: "2023-05-30T16:20:00Z",
    totalBookings: 4,
    status: "active",
  },
];

export const mockBookings = [
  {
    id: "1",
    homestayId: "1",
    homestayName: "Sunset Beach Villa",
    customerId: "1",
    customerName: "Nguyễn Văn A",
    checkIn: "2023-06-15",
    checkOut: "2023-06-20",
    guests: 4,
    totalPrice: 6000000,
    status: "completed",
    createdAt: "2023-05-10T09:30:00Z",
    paymentStatus: "paid",
    paymentMethod: "credit_card",
  },
  {
    id: "2",
    homestayId: "2",
    homestayName: "Mountain Retreat",
    customerId: "2",
    customerName: "Trần Thị B",
    checkIn: "2023-07-05",
    checkOut: "2023-07-10",
    guests: 2,
    totalPrice: 4250000,
    status: "confirmed",
    createdAt: "2023-06-01T14:45:00Z",
    paymentStatus: "paid",
    paymentMethod: "bank_transfer",
  },
  {
    id: "3",
    homestayId: "3",
    homestayName: "Riverside Cottage",
    customerId: "3",
    customerName: "Lê Văn C",
    checkIn: "2023-08-20",
    checkOut: "2023-08-25",
    guests: 3,
    totalPrice: 4750000,
    status: "cancelled",
    createdAt: "2023-07-15T11:20:00Z",
    paymentStatus: "refunded",
    paymentMethod: "credit_card",
  },
  {
    id: "4",
    homestayId: "4",
    homestayName: "City Center Apartment",
    customerId: "4",
    customerName: "Phạm Thị D",
    checkIn: "2023-09-10",
    checkOut: "2023-09-15",
    guests: 2,
    totalPrice: 5500000,
    status: "pending",
    createdAt: "2023-08-05T16:30:00Z",
    paymentStatus: "pending",
    paymentMethod: "pending",
  },
  {
    id: "5",
    homestayId: "5",
    homestayName: "Lakeside Villa",
    customerId: "5",
    customerName: "Hoàng Văn E",
    checkIn: "2023-10-25",
    checkOut: "2023-11-01",
    guests: 6,
    totalPrice: 10500000,
    status: "confirmed",
    createdAt: "2023-09-20T10:15:00Z",
    paymentStatus: "paid",
    paymentMethod: "bank_transfer",
  },
  {
    id: "6",
    homestayId: "1",
    homestayName: "Sunset Beach Villa",
    customerId: "1",
    customerName: "Nguyễn Văn A",
    checkIn: "2023-12-10",
    checkOut: "2023-12-15",
    guests: 5,
    totalPrice: 6000000,
    status: "confirmed",
    createdAt: "2023-11-05T08:45:00Z",
    paymentStatus: "paid",
    paymentMethod: "credit_card",
  },
  {
    id: "7",
    homestayId: "2",
    homestayName: "Mountain Retreat",
    customerId: "5",
    customerName: "Hoàng Văn E",
    checkIn: "2024-01-05",
    checkOut: "2024-01-10",
    guests: 3,
    totalPrice: 4250000,
    status: "pending",
    createdAt: "2023-12-01T13:30:00Z",
    paymentStatus: "pending",
    paymentMethod: "pending",
  },
];

export const mockReviews = [
  {
    id: "1",
    homestayId: "1",
    homestayName: "Sunset Beach Villa",
    customerId: "1",
    customerName: "Nguyễn Văn A",
    rating: 5,
    comment: "Tuyệt vời! Cảnh đẹp, phòng sạch sẽ và nhân viên rất thân thiện.",
    createdAt: "2023-06-21T10:30:00Z",
    status: "approved",
  },
  {
    id: "2",
    homestayId: "2",
    homestayName: "Mountain Retreat",
    customerId: "2",
    customerName: "Trần Thị B",
    rating: 4,
    comment:
      "Không gian yên tĩnh, thích hợp để nghỉ ngơi. Tuy nhiên, đường đi hơi khó tìm.",
    createdAt: "2023-07-11T15:45:00Z",
    status: "approved",
  },
  {
    id: "3",
    homestayId: "3",
    homestayName: "Riverside Cottage",
    customerId: "3",
    customerName: "Lê Văn C",
    rating: 3,
    comment: "Vị trí đẹp nhưng phòng hơi nhỏ và thiếu một số tiện nghi cơ bản.",
    createdAt: "2023-08-26T09:15:00Z",
    status: "pending",
  },
  {
    id: "4",
    homestayId: "4",
    homestayName: "City Center Apartment",
    customerId: "4",
    customerName: "Phạm Thị D",
    rating: 5,
    comment:
      "Vị trí trung tâm, thuận tiện đi lại. Phòng rộng rãi và đầy đủ tiện nghi.",
    createdAt: "2023-09-16T14:20:00Z",
    status: "approved",
  },
  {
    id: "5",
    homestayId: "5",
    homestayName: "Lakeside Villa",
    customerId: "5",
    customerName: "Hoàng Văn E",
    rating: 4,
    comment:
      "Cảnh quan tuyệt đẹp, không gian rộng rãi. Giá hơi cao nhưng xứng đáng.",
    createdAt: "2023-11-02T11:30:00Z",
    status: "rejected",
  },
];

export const mockRevenueData = [
  { month: "Jan", revenue: 25000000 },
  { month: "Feb", revenue: 32000000 },
  { month: "Mar", revenue: 28000000 },
  { month: "Apr", revenue: 35000000 },
  { month: "May", revenue: 40000000 },
  { month: "Jun", revenue: 45000000 },
  { month: "Jul", revenue: 50000000 },
  { month: "Aug", revenue: 48000000 },
  { month: "Sep", revenue: 52000000 },
  { month: "Oct", revenue: 55000000 },
  { month: "Nov", revenue: 58000000 },
  { month: "Dec", revenue: 65000000 },
];

export const mockBookingStats = {
  total: 120,
  completed: 85,
  cancelled: 15,
  pending: 10,
  confirmed: 10,
  monthlyStats: [
    { month: "Jan", bookings: 8 },
    { month: "Feb", bookings: 10 },
    { month: "Mar", bookings: 12 },
    { month: "Apr", bookings: 9 },
    { month: "May", bookings: 11 },
    { month: "Jun", bookings: 15 },
    { month: "Jul", bookings: 18 },
    { month: "Aug", bookings: 14 },
    { month: "Sep", bookings: 10 },
    { month: "Oct", bookings: 8 },
    { month: "Nov", bookings: 7 },
    { month: "Dec", bookings: 8 },
  ],
};

export const mockRoomUsageStats = {
  totalHomestays: 15,
  activeHomestays: 12,
  maintenanceHomestays: 2,
  inactiveHomestays: 1,
  occupancyRate: 75,
  averageStayDuration: 4.5,
  monthlyOccupancy: [
    { month: "Jan", rate: 65 },
    { month: "Feb", rate: 70 },
    { month: "Mar", rate: 68 },
    { month: "Apr", rate: 72 },
    { month: "May", rate: 75 },
    { month: "Jun", rate: 85 },
    { month: "Jul", rate: 90 },
    { month: "Aug", rate: 88 },
    { month: "Sep", rate: 80 },
    { month: "Oct", rate: 75 },
    { month: "Nov", rate: 70 },
    { month: "Dec", rate: 78 },
  ],
};

export const mockReviewStats = {
  totalReviews: 95,
  averageRating: 4.6,
  ratingDistribution: [
    { rating: 5, count: 60 },
    { rating: 4, count: 25 },
    { rating: 3, count: 8 },
    { rating: 2, count: 2 },
    { rating: 1, count: 0 },
  ],
  approvedReviews: 85,
  pendingReviews: 8,
  rejectedReviews: 2,
};
