export function randomBankInfo() {
  const banks = [
    "Vietcombank",
    "VietinBank",
    "BIDV",
    "Techcombank",
    "ACB",
    "Sacombank",
    "MB Bank",
    "VPBank",
    "SHB",
    "TPBank",
    "SeABank",
    "HDBank",
    "Eximbank",
    "OCB",
    "ABBANK",
    "SCB",
    "BacABank",
    "BaoVietBank",
    "PG Bank",
    "NCB",
    "VIB",
    "LienVietPostBank",
    "NamABank",
    "VietBank",
    "KienlongBank",
    "OceanBank",
    "PVcomBank",
    "Saigonbank",
    "DongABank",
    "GPBank",
  ];

  const firstNames = [
    "Nguyễn",
    "Trần",
    "Lê",
    "Phạm",
    "Hoàng",
    "Huỳnh",
    "Vũ",
    "Võ",
    "Đặng",
    "Bùi",
    "Đỗ",
    "Hồ",
    "Ngô",
    "Dương",
    "Lý",
    "Tạ",
    "Mai",
    "Hà",
    "Châu",
    "Tô",
    "Cao",
    "Kiều",
    "Trịnh",
    "Quách",
    "Triệu",
    "La",
    "Phan",
    "Thái",
    "Đinh",
    "Lâm",
  ];

  const middleNames = [
    "Văn",
    "Thị",
    "Hữu",
    "Đức",
    "Ngọc",
    "Minh",
    "Thanh",
    "Xuân",
    "Gia",
    "Trọng",
    "Công",
    "Thành",
    "Nhật",
    "Thái",
    "Phúc",
    "Bảo",
    "Tuấn",
    "Khánh",
    "Quốc",
    "Tiến",
    "Viết",
    "Hải",
    "Tấn",
    "Phương",
    "Anh",
    "Đăng",
    "Thế",
    "Duy",
    "Thiện",
    "Tường",
  ];

  const lastNames = [
    "Anh",
    "Bình",
    "Châu",
    "Dũng",
    "Hà",
    "Hằng",
    "Hạnh",
    "Hiếu",
    "Hòa",
    "Hương",
    "Khánh",
    "Lan",
    "Linh",
    "Nam",
    "Ngân",
    "Ngọc",
    "Phong",
    "Quân",
    "Sơn",
    "Trang",
    "Tuấn",
    "Thảo",
    "Vân",
    "Việt",
    "Yến",
    "Tú",
    "Tiến",
    "Tâm",
    "Nhi",
    "Hùng",
  ];

  const randomFrom = (arr: string[]) =>
    arr[Math.floor(Math.random() * arr.length)];
  const randomDigits = (length: number) =>
    Array.from({ length }, () => Math.floor(Math.random() * 10)).join("");

  const bank = randomFrom(banks);
  const accountNumber = randomDigits(Math.floor(Math.random() * 5) + 10); // từ 10 đến 14 số
  const accountHolder = `${randomFrom(firstNames)} ${randomFrom(middleNames)} ${randomFrom(lastNames)}`;

  return {
    bank,
    accountNumber,
    accountHolder,
  };
}
